davidsonfellipe/awesome-wpo

- README.md
- TALKS.md
Added CSS sprite generator and Grunt-sprite-css-replace
> Added CSS sprite generator

- README.md
I'm not sure about the category... Can be Sprite or SVG.
You choose! :)
> Added grunt svg sprite

- README.md
Hi, I'm adding an open-source tool I wrote: https://github.com/gmetais/YellowLabTools
> New tool: Yellow Lab Tools

- README.md
It's the best tool to optimize SVG on the web. You really need this =)
> Add SVG OMG link

- README.md
If you have any questions - feel free to ask
> Added PerfTests - performance tests of JavaScript inheritance models

- ARTICLES.md
- README.md
> Update readme.md and organize articles

- TALKS.md
> Add Browser Rendering Optimization course

- README.md
Added beeswithmachineguns project into Webserver Benchmarks section.
> Added beeswithmachineguns project

- README.md
Books by Stoyan Stefanov added :)
> books added

- README.md
Add Resource Hints specification
> Add Resource Hints specification

- README.md
Added a new CDN utility that I recently open sourced.
> Added CDN Utility

- README.md
> Add the book 'Async & Performance'  and benchmark minimal-stats.js

- README.md
Added “Lean Websites” SitePoint book by Barbara Bermes.
> Added “Lean Websites” book by Barbara Bermes

- README.md
I'm adding the cool PWA auditing tool from the Chrome team. It is a very helpful performance check list for the modern web, specially on mobile.
> Add Lighthouse

- README.md
> Add Speed Racer

- PEOPLE.md
Add [Sam Saccone](https://twitter.com/samccone) to people list. :tada:
> Add to people list

- PEOPLE.md
- README.md
Hi @davidsonfellipe, I've writing a book on HTTP/2 (https://www.manning.com/books/http2-in-action) and the performance improvements it is looking to give. The first 3 chapters have just been published under Manning's early access program (MEAP). I wonder if you would include a link to it here since you don't seem to have any links to HTTP/2 resources yet?
Thanks,
Barry
> Add HTTP/2 in Action book and author (myself).

- README.md
Hi Fellipe!
I'm the author of the early release book "Web Components in Action" with Manning Publications. It was recommended that I add on to your list. I know it's largely about web performance, but I do see some Web Component (and other resources) here - so if you think it's appropriate and wouldn't mind adding my book, I'd be grateful.
thank you!
> Added Web Components in Action book

- ARTICLES.md
This proposal adds _Philip Walton's_ [Idle Until Urgent](https://philipwalton.com/articles/idle-until-urgent/).
Thank you,
> Adding Idle Until Urgent

- PEOPLE.md
Including Eric Bidelman, Surma, Alex Russell, and Rob Dodson
> Added 4 four more people

- README.md
Added Web.dev https://web.dev/
> Added Web.dev

- README.md
Maybe wrong section, i not finded better (sorry)
> Added Awesome Webpack Perf list (by @iamakulov)

- README.md
Add cloudflare that provides Tiered pricing and free-tier cdn services.
> Add cloduflare cdn

- content/TALKS.md
> Add some by that were missing from the Talks section

- content/BLOGS.md
> Test Deploy preview

- content/ARTICLES.md
Add article How to read a WebPageTest Waterfall View chart by @nooshu
https://nooshu.github.io/blog/2019/10/02/how-to-read-a-wpt-waterfall-chart/
> Add article How to read a WebPageTest Waterfall View chart

- content/ARTICLES.md
Add article 
WebPageTest comparison URL generator by @nooshu
> Add  WebPageTest comparison URL generator article

- README.md
Tapnesh is a CLI bash script that will optimize all your images in parallel easily and efficiently! You can use it on a single image or specify a whole directory.
> Add Tapnesh

- README.md
Fixes this 404 https://github.com/davidsonfellipe/awesome-wpo/blob/master/BLOGS.md.
> Docs: Fix BLOGS broken link

- README.md
Added Google Developers Case Studies to Case Studies
> Added Google Developers Case Studies

- README.md
> Add warning for JSperf.com

- README.md
Added performance.now() and #PerfMatters to conferences
> Added two more conferences

- README.md
- Tool
[AtBuild](https://github.com/jarred-sumner/atbuild) is a new JS code generation tool that makes it easier to programmatically generate JS code
> Add atbuild to readme

- README.md
- Tool
- Adding information for RUM solution bytesmatter.io with free tier
> Adding info for BytesMatter RUM solution with free tier

- README.md
- Tool
Hey there!
My team published a small tool that we use for images optimization. I think it's kinda suitable for this list.
Here it is: https://github.com/funbox/optimizt
> Add Optimizt

- content/ARTICLES.md
This article contains lots of information about running a WebPageTest test
> Add link to latest WPT article.

- README.md
- Tool
Adds [bundle-stats](https://github.com/relative-ci/bundle-stats) - bundle analysis and side by side comparison between different builds
> Add bundle-stats

- CODE_OF_CONDUCT.md
- Docs
- chore(docs): add code of conduct
> chore(docs): add code of conduct

- README.md
- Tool
Add a section about uptime, with different commercial tools
> chore(docs): Add section about uptime

- README.md
- Chore
- Deleting broken links
> Delete broken links: cdnex and spriteme

- README.md
- Tool
Add Web Performance Report to WPO List. Like the other tools on the web performance list, it is free.
> Add WebPerformance Report to WPO List

- README.md
> chore(docs): remove nodown

- README.md
- Tool
Added another Uptime Monitor Service that offers a free forever plan.
> Added Uptime Monitor RoboMiri

- .github/PULL_REQUEST_TEMPLATE.md
- Templates
- Add Meetups to PR template
> chore(github): add Meetups to PR template

- content/BLOGS.md
- Blogs
- Remove blog `monsiteestlent`
> docs(blogs): remove blog monsiteestlent

- website/src/components/Header.js
- Website
- Remove the link to people page
> chore(website): remove link to people page

- package.json
- Chore
- Remove people.md from the lint
> chore(lint): remove people.md from the lint

- README.md
- Docs
- Remove references to people.md
> chore(docs): remove references to people.md

- README.md
- Tool
- added statuslist.app to the list of application monitors
> Add statuslist.app to monitoring section

- README.md
Shortpixel - A Free Image Optimizer In Real Time
- Tool
I have added "https://shortpixel.com/online-image-compression" Image Optimizer Tool Which Allow us to Compress Image and Convert the image into next generation image format WebP/AVIF
> Added New Image Optimizer

- .vscode/settings.json
- README.md
- content/README.md
- Tool
Add `Lightest app` website
> Add Lightest app

- COURSES.md
- Courses
- Courses on Website Performance Optimization
> docs(courses): improve text for courses section

- README.md
- Docs
- Improves the intro text
- Fixes some typos
> docs(main-readme): improves the intro text and fixes some typos

- README.md
- Tool
- Adds the ResponsiveImage project (https://github.com/simonihmig/responsive-image) to the list of Image Optimizers
> Add ResponsiveImage project to Image Optimizers
